version: "3.7"

services:
  fin_api:
    image: postgres
    container_name: fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/POSTGRES_DB
  app:
    build: .
    container_name: test
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - fin_api
    depends_on:
      - fin_api
volumes:
  pgdata:
    driver: local
